bhf/bhf/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from inventory.views import homepage

urlpatterns = [
    # Examples:
    # url(r'^$', 'bhf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', homepage, name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^inventory/', include('inventory.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        name='auth_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='auth_logout'),
]

if settings.DEBUG:

    # Appending url pattern for serving user uploaded files
    urlpatterns.append(url(r'^media/(?P<path>.*)', 'django.views.static.serve',
                           {'document_root': settings.MEDIA_ROOT}))

bhf/inventory/urls.py
from django.conf.urls import url
from inventory.views import list_products, edit_product, new_product, \
    list_categories, edit_category, new_category, list_subcategories,  \
    edit_subcategory, new_subcategory


urlpatterns = [
    url(r'^product/$', list_products, name='product_list'),
    url(r'^product/new/$', new_product, name='new_product'),
    url(r'^product/(?P<prod_var_id>[0-9]+)/$', edit_product,
        name='edit_product'),
    url(r'^category/$', list_categories, name='category_list'),
    url(r'^category/new$', new_category, name='new_category'),
    url(r'^category/(?P<category_id>[0-9]+)/$', edit_category,
        name='edit_category'),
    url(r'^category/(?P<category_id>[0-9]+)/subcategory/new$', new_subcategory,
        name='new_subcategory'),
    url(r'^category/(?P<category_id>[0-9]+)/subcategory/$', list_subcategories,
        name='subcategory_list'),
    url(r'^category/(?P<category_id>[0-9]+)/subcategory/(?P<subcategory_id>[0-9]+)/$',
        edit_subcategory, name='edit_subcategory'),
]

bhf/inventory/models.py
from django.db import models


def upload_handler(instance, filename):
    """Returns the relative file path for user uploaded images."""
    return 'img/{}'.format(filename)


class Image(models.Model):
    """Model definition for images."""
    image_file = models.ImageField(upload_to=upload_handler, blank=True)
    thumbnail_file = models.ImageField(upload_to=upload_handler, blank=True)
    image_alt_text = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.image_alt_text


class Category(models.Model):
    """Model definition for categories."""
    image = models.ManyToManyField(Image)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1200)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    """Model definition for subcategories."""
    image = models.ManyToManyField(Image)
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1200)

    def __str__(self):
        return self.name


class Color(models.Model):
    """Model definition for colors."""
    color = models.CharField(max_length=100)

    def __str__(self):
        return self.color


class Size(models.Model):
    """Model definition for sizes."""
    size_code = models.CharField(max_length=100, blank=True)
    width = models.CharField(max_length=100, blank=True)
    length = models.CharField(max_length=100, blank=True)
    depth = models.CharField(max_length=100, blank=True)

    def __str__(self):
        if not self.size_code:
            return self.width + ':' + self.length + ':' + self.depth
        else:
            return self.size_code


class Status(models.Model):
    """Model definition for status."""
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.status


class Supplier(models.Model):
    """Model definition for suppliers."""
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    address2 = models.CharField(max_length=200)
    city = models.CharField(max_length=80)
    state = models.CharField(max_length=50)
    zip = models.IntegerField()
    phone = models.BigIntegerField(blank=True, null=True)
    fax = models.BigIntegerField(blank=True, null=True)
    email = models.EmailField(max_length=200, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    """Model definition for products."""
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    short_description = models.TextField(max_length=250, blank=True)
    category = models.ManyToManyField(Category, blank=True)
    subcategory = models.ManyToManyField(Subcategory, blank=True)

    def __str__(self):
        return self.name


class ProductVariant(models.Model):
    """Model definition for product variants."""
    product = models.ForeignKey(Product)
    color = models.ForeignKey(Color)
    size = models.ForeignKey(Size)
    status = models.ForeignKey(Status)
    supplier = models.ManyToManyField(Supplier)
    image = models.ManyToManyField(Image, blank=True)
    special_order = models.BooleanField(default=False)
    upc = models.IntegerField(blank=True, null=True)
    weight = models.CharField(max_length=100, blank=True)
    code = models.CharField(max_length=100, blank=True)
    msrp = models.FloatField(default=0)
    quantity_on_hand = models.IntegerField(default=0)

    def __str__(self):
        return self.product.name

bhf/inventory/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from .forms import CategoryForm, ColorForm, ImageForm, ProductForm, \
    ProductVariantForm, SizeForm, StatusForm, SubcategoryForm, SupplierForm
from .models import Category, Color, Image, Product, ProductVariant, Size, \
    Status, Subcategory, Supplier


@login_required(login_url='/login')
def homepage(request):
    """Builds a dashboard with inventory summary."""
# Counts list contains the number of inventory items for the summary.
    counts = {}
    counts['category_count'] = Category.objects.count()
    counts['subcategory_count'] = Subcategory.objects.count()
    counts['product_count'] = Product.objects.count()
    counts['prod_var_count'] = ProductVariant.objects.count()
    return render(request, 'index.html', counts)


@login_required(login_url='/login')
def list_products(request):
    """Lists products with some key attributes."""
    product_list = ProductVariant.objects.order_by('product__name')
    context = {'product_list': product_list}
    return render(request, 'list_products.html', context)


@login_required(login_url='/login')
def new_product(request):
    """Add a new product and define all its attributes."""
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the product and product variant forms.
        prod_form = ProductForm(request.POST)
        prodv_form = ProductVariantForm(request.POST)
        # If the form data is valid, save it.
        if prod_form.is_valid() and prodv_form.is_valid():
            updated_prod = prod_form.save()
            updated_prod_var = prodv_form.save(commit=False)
            updated_prod_var.product = updated_prod
            updated_prod_var.save()
            prodv_form.save_m2m()
            return redirect('product_list')
    # If this view was called upon a GET, render the form.
    else:
        prod_form = ProductForm()
        prodv_form = ProductVariantForm()
    return render(request, 'new_product.html', {'prod_form': prod_form,
                                                'prodv_form': prodv_form})


@login_required(login_url='/login')
def edit_product(request, prod_var_id):
    """Edit all attributes of a product."""
    # Fetch the product and product variant objects to edit.
    prod_var = get_object_or_404(ProductVariant, pk=prod_var_id)
    product = prod_var.product
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the product and product variant forms.
        prod_form = ProductForm(request.POST, instance=product)
        prodv_form = ProductVariantForm(request.POST, instance=prod_var)
        # If the form data is valid, save it.
        if prod_form.is_valid() and prodv_form.is_valid():
            updated_prod = prod_form.save()
            updated_prod_var = prodv_form.save(commit=False)
            updated_prod_var.product = updated_prod
            updated_prod_var.save()
            prodv_form.save_m2m()
            return redirect('product_list')
    # If this view was called upon a GET, render the form.
    else:
        prod_form = ProductForm(instance=product)
        prodv_form = ProductVariantForm(instance=prod_var)
    return render(request, 'edit_product.html', {'prod_var': prod_var,
                                                 'product': product,
                                                 'prod_form': prod_form,
                                                 'prodv_form': prodv_form})


@login_required(login_url='/login')
def list_categories(request):
    """Lists categories with some key attributes."""
    category_list = Category.objects.order_by('name')
    context = {'category_list': category_list}
    return render(request, 'list_categories.html', context)


@login_required(login_url='/login')
def new_category(request):
    """Add new category and define all its attributes."""
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the category form.
        cat_form = CategoryForm(request.POST)
        # If the form data is valid, save it.
        if cat_form.is_valid():
            cat_form.save()
            return redirect('category_list')
    # If this view was called upon a GET, render the form.
    else:
        cat_form = CategoryForm()
    return render(request, 'new_category.html', {'cat_form': cat_form})


@login_required(login_url='/login')
def edit_category(request, category_id):
    """Edit all attributes of a category."""
    # Fetch the category object to edit.
    category = get_object_or_404(Category, pk=category_id)
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the category form.
        cat_form = CategoryForm(request.POST, instance=category)
        # If the form data is valid, save it.
        if cat_form.is_valid():
            cat_form.save()
            return redirect('category_list')
    # If this view was called upon a GET, render the form.
    else:
        cat_form = CategoryForm(instance=category)
    return render(request, 'edit_category.html', {'cat_form': cat_form,
                                                  'category': category})


@login_required(login_url='/login')
def list_subcategories(request, category_id):
    """Lists subcategories with some key attributes."""
    category = get_object_or_404(Category, pk=category_id)
    subcategory_list = category.subcategory_set.order_by('name')
    context = {'category': category, 'subcategory_list': subcategory_list}
    return render(request, 'list_subcategories.html', context)


@login_required(login_url='/login')
def new_subcategory(request, category_id):
    """Add new subcategory and define all its attributes."""
    # category = get_object_or_404(Category, pk=category_id)
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the subcategory form.
        subcat_form = SubcategoryForm(request.POST)
        # If the form data is valid, save it.
        if subcat_form.is_valid():
            subcat_form.save()
            return redirect('subcategory_list', category_id)
    # If this view was called upon a GET, render the form.
    else:
        subcat_form = SubcategoryForm()
    return render(request, 'new_subcategory.html',
                  {'subcat_form': subcat_form, 'category_id': category_id})


@login_required(login_url='/login')
def edit_subcategory(request, category_id, subcategory_id):
    """Edit all attributes of a subcategory."""
    category = get_object_or_404(Category, pk=category_id)
    subcategory = category.subcategory_set.get(pk=subcategory_id)
    # Check if a POST has been submitted.
    if request.POST:
        # Generate the subcategory form.
        subcat_form = SubcategoryForm(request.POST, instance=subcategory)
        # If the form data is valid, save it.
        if subcat_form.is_valid():
            subcat_form.save()
            return redirect('subcategory_list', category_id)
    # If this view was called upon a GET, render the form.
    else:
        subcat_form = SubcategoryForm(instance=subcategory)
    return render(request, 'edit_subcategory.html',
                  {'subcat_form': subcat_form, 'category_id': category_id,
                   'subcategory': subcategory})

bhf/inventory/templates/edit_subcategory.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - Edit Subcategory
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'inventory/css/edit_category.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="breadcrumb-wrapper">
            <ul class="breadcrumb">
                <li><a href="{% url "home" %}">Home</a></li>
                <li><a href="{% url "category_list" %}">Categories</a></li>
                <li>{{ category_id }}</li>
                <li><a href="{% url "subcategory_list" category_id %}">
                    Subcategories</a></li>
                <li class="active">{{ subcategory.id }}</li>
            </ul>
        </div>
        <div class="page-header">
            <h3>Edit Subcategory</h3>
        </div>

        <form class="form-horizontal" method="post"
              action="{% url 'edit_subcategory' category_id subcategory.id %}">
            {% csrf_token %}

            <!-- Category - select -->
            <div class="form-group">
                {% if subcat_form.category.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in subcat_form.category.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_category" class="control-label col-xs-2">Category</label>

                <div class="col-xs-10">
                    {{ subcat_form.category }}
                </div>
            </div>

            <!-- Name - text input -->
            <div class="form-group">
                {% if subcat_form.name.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in subcat_form.name.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_name" class="control-label col-xs-2">Name</label>
                <div class="col-xs-10">
                    {{ subcat_form.name }}
                </div>
            </div>

            <!-- Description - text area "-->
            <div class="form-group">
                {% if subcat_form.description.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in subcat_form.description.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
               <label for="id_description" class="control-label col-xs-2">
                    Description</label>
                <div class="col-xs-10">
                    {{ subcat_form.description }}
                </div>
            </div>

            <!-- Render Description - read-only -->
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="button" id="render" class="btn btn-default">
                        Render</button>
                </div>

                <div class="col-xs-offset-2 col-xs-10">
                    <div class="well output_box" id="output_box">
                        <i>Click the above button to render description here!</i>
                    </div>
                </div>
            </div>

            <!-- Image - select multiple -->
            <div class="form-group">
                {% if subcat_form.image.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in subcat_form.image.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_image" class="control-label col-xs-2">
                    Image</label>
                <div class="col-xs-5">
                    {{ subcat_form.image }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-offset-2">
                </div>
                {% for img in subcategory.image.all %}
                    {% if forloop.first %}
                        <div class="col-xs-offset-2 col-xs-2">
                    {% else %}
                        <div class="col-xs-2">
                    {% endif %}
                        <a href="#" class="thumbnail"> <img
                              src="{{ img.image_file.url }}"></a>
                        </div>
                {% endfor %}
                </div>
                <!-- Submit button -->
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="submit" class="save btn btn-default">Save
                    </button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript"
            src="{% static 'inventory/js/edit_category.js' %}"></script>
{% endblock %}

bhf/inventory/templates/new_product.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
    {{ block.super }} - New product
{% endblock %}

{% block stylesheets %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'inventory/css/edit_category.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="breadcrumb-wrapper">
            <ul class="breadcrumb">
                <li><a href="{% url "home" %}">Home</a></li>
                <li><a href="{% url "product_list" %}">Products</a></li>
                <li class="active">New</li>
            </ul>
        </div>
        <div class="page-header">
            <h3>New product</h3>
        </div>
        <form class="form-horizontal" method="post"
              action="{% url 'new_product' %}">{% csrf_token %}

            <!-- Name - text input -->
            <div class="form-group">
                {% if prod_form.name.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prod_form.name.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_name" class="control-label col-xs-2">Name
                </label>
                <div class="col-xs-10">
                    {{ prod_form.name }}
                </div>
            </div>

            <!-- Description - text area "-->
            <div class="form-group">
                {% if prod_form.description.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prod_form.description.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_description" class="control-label col-xs-2">
                    Description
                </label>
                <div class="col-xs-10">
                    {{ prod_form.description }}
                </div>
            </div>

            <!-- Render Description - read-only -->
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="button" id="render_desc" class="btn btn-default">
                        Render
                    </button>
                </div>
                <div class="col-xs-offset-2 col-xs-10">
                    <div class="well output_box" id="desc_output_box">
                        <i>Click the above button to render description
                            here!</i>
                    </div>
                </div>
            </div>

            <!-- Short description - text area "-->
            <div class="form-group">
                {% if prod_form.short_description.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prod_form.short_description.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_short_description" class="control-label col-xs-2">
                    Short description
                </label>
                <div class="col-xs-10">
                    {{ prod_form.short_description }}
                </div>
            </div>

            <!-- Render short description - read-only -->
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="button" id="render_sh_desc" class="btn btn-default">
                        Render
                    </button>
                </div>
                <div class="col-xs-offset-2 col-xs-10">
                    <div class="well output_box" id="sh_desc_output_box">
                        <i>Click the above button to render short description
                            here!</i>
                    </div>
                </div>
            </div>

            <!-- Category - select -->
            <div class="form-group">
                {% if prod_form.category.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prod_form.category.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_category" class="control-label col-xs-2">
                    Category
                </label>
                <div class="col-xs-5">
                    {{ prod_form.category }}
                </div>
            </div>

            <!-- Subcategory - select -->
            <div class="form-group">
                {% if prod_form.subcategory.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prod_form.subcategory.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_subcategory" class="control-label col-xs-2">
                    Subcategory
                </label>
                <div class="col-xs-5">
                    {{ prod_form.subcategory }}
                </div>
            </div>

            <!-- Color - select -->
            <div class="form-group">
                {% if prodv_form.color.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.color.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_color" class="control-label col-xs-2">
                    Color
                </label>
                <div class="col-xs-5">
                    {{ prodv_form.color }}
                </div>
            </div>

            <!-- Size - select -->
            <div class="form-group">
                {% if prodv_form.size.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.size.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_size" class="control-label col-xs-2">Size</label>
                <div class="col-xs-5">
                    {{ prodv_form.size }}
                </div>
            </div>

            <!-- Status - select -->
            <div class="form-group">
                {% if prodv_form.status.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.status.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_status" class="control-label col-xs-2">Status</label>
                <div class="col-xs-5">
                    {{ prodv_form.status }}
                </div>
            </div>

            <!-- Supplier - select multiple -->
            <div class="form-group">
                {% if prodv_form.supplier.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.supplier.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_supplier" class="control-label col-xs-2">Supplier</label>
                <div class="col-xs-5">
                    {{ prodv_form.supplier }}
                </div>
            </div>

            <!-- Image - select multiple -->
            <div class="form-group">
                {% if prodv_form.image.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.image.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_image" class="control-label col-xs-2">Image</label>
                <div class="col-xs-5">
                    {{ prodv_form.image }}
                </div>
            </div>
            <div class="row">
                <div class="col-xs-offset-2">
                </div>
                {% for img in prod_var.image.all %}
                    {% if forloop.first %}
                        <div class="col-xs-offset-2 col-xs-2">
                    {% else %}
                        <div class="col-xs-2">
                    {% endif %}
                    <a href="#" class="thumbnail"> <img
                          src="{{ img.image_file.url }}"></a>
                    </div>
                {% endfor %}
            </div>

            <!-- UPC - number input -->
            <div class="form-group">
                {% if prodv_form.upc.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.upc.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_upc" class="control-label col-xs-2">UPC</label>
                <div class="col-xs-5">
                    {{ prodv_form.upc }}
                </div>
            </div>

            <!-- Weight - text input -->
            <div class="form-group">
                {% if prodv_form.weight.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.weight.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_weight"
                       class="control-label col-xs-2">Weight</label>
                <div class="col-xs-5">
                    {{ prodv_form.weight }}
                </div>
            </div>

            <!-- Code - text input -->
            <div class="form-group">
                {% if prodv_form.code.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.code.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_code"
                       class="control-label col-xs-2">Code</label>
                <div class="col-xs-5">
                    {{ prodv_form.code }}
                </div>
            </div>

            <!-- MSRP - number input -->
            <div class="form-group">
                {% if prodv_form.msrp.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.msrp.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_msrp"
                       class="control-label col-xs-2">MSRP ($)</label>
                <div class="col-xs-5">
                    {{ prodv_form.msrp }}
                </div>
            </div>

            <!-- Special order - number input -->
            <div class="form-group">
                {% if prodv_form.special_order.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.special_order.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_special_order"
                       class="control-label col-xs-2">Special order</label>
                <div class="col-xs-5">
                    {{ prodv_form.special_order }}
                </div>
            </div>

            <!-- Quantity on hand - number input -->
            <div class="form-group">
                {% if prodv_form.quantity_on_hand.errors %}
                    <div class="col-xs-offset-2 col-xs-10">
                        {% for error in prodv_form.quantity_on_hand.errors %}
                            <p class="text-danger">{{ error|escape }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <label for="id_quantity_on_hand"
                       class="control-label col-xs-2">Quantity on hand</label>
                <div class="col-xs-5">
                    {{ prodv_form.quantity_on_hand }}
                </div>
            </div>

            <!-- Submit button -->
            <div class="form-group">
                <div class="col-xs-offset-2 col-xs-10">
                    <button type="submit" class="save btn btn-default">Save
                    </button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script type="text/javascript"
            src="{% static 'inventory/js/edit_product.js' %}"></script>
{% endblock %}